// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: protodef/api/jsonapi/request.proto

package jsonapi

import (
	_ "github.com/mwitkow/go-proto-validators"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A `GetRequest` defines various url and query parameters that could be passed
// in a HTTP **GET** request to a singular resource. Majority of the request
// parameters are identical or similar to [jsonapi](http://jsonapi.org).
type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An unique identifier, for example:
	// "/users/34"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// include query parameter to retrieve any particular or particular
	// combination of relationships. Multiple include values are delimited by
	// comma(,).
	//
	// For example,
	//      /{resource_name}/13?include=baz
	//      /{resource_name}/13?include=baz,bot
	Include string `protobuf:"bytes,2,opt,name=include,proto3" json:"include,omitempty"`
	// fields query parameter to retrieve any particular or any particular
	// combination of attributes. Multiple fields values are delimited by comma(,).
	//
	// For example
	//      /{resource_name}/29?fields=foo
	//      /{resource_name}/?fields=foo,bar
	Fields string `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRequest) GetInclude() string {
	if x != nil {
		return x.Include
	}
	return ""
}

func (x *GetRequest) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

// A `GetEmailRequest` is identical to GetRequest except `email` id used as unique identifier.
type GetEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Email id
	// "/users/newman@seinfeld.org"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// include query parameter to retrieve any particular or particular
	// combination of relationships. Multiple include values are delimited by
	// comma(,).
	//
	// For example,
	//          /{resource_name}/13?include=baz
	//          /{resource_name}/13?include=baz,bot
	Include string `protobuf:"bytes,2,opt,name=include,proto3" json:"include,omitempty"`
	// fields query parameter to retrieve any particular or any particular
	// combination of attributes. Multiple fields values are delimited by comma(,).
	//
	// For example,
	//          /{resource_name}/29?fields=foo
	//          /{resource_name}/?fields=foo,bar
	Fields string `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
}

func (x *GetEmailRequest) Reset() {
	*x = GetEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailRequest) ProtoMessage() {}

func (x *GetEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailRequest.ProtoReflect.Descriptor instead.
func (*GetEmailRequest) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{1}
}

func (x *GetEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetEmailRequest) GetInclude() string {
	if x != nil {
		return x.Include
	}
	return ""
}

func (x *GetEmailRequest) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

// A `GetRequestWithFields` is a subset of GetRequest which only allow the fields parameter.
type GetRequestWithFields struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An unique identifier, for example:
	// "/users/34"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// fields query parameter to retrieve any particular or any particular
	// combination of attributes. Multiple fields values are delimited by comma(,).
	//
	// For example
	// /{resource_name}/29?fields=foo
	// /{resource_name}/?fields=foo,bar
	Fields string `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
}

func (x *GetRequestWithFields) Reset() {
	*x = GetRequestWithFields{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestWithFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestWithFields) ProtoMessage() {}

func (x *GetRequestWithFields) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestWithFields.ProtoReflect.Descriptor instead.
func (*GetRequestWithFields) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequestWithFields) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRequestWithFields) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

// A `RelationshipRequest` defines the url parameter for relationship resources
// that are given in the links field of relationship object
type RelationshipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An unique identifier, for example:
	// "/users/45/roles" or "/users/45/relationships/roles"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RelationshipRequest) Reset() {
	*x = RelationshipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipRequest) ProtoMessage() {}

func (x *RelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipRequest.ProtoReflect.Descriptor instead.
func (*RelationshipRequest) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{3}
}

func (x *RelationshipRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// A `RelationshipRequestWithPagination` is a `RelationshipRequest` with pagination
type RelationshipRequestWithPagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pagenum  int64 `protobuf:"varint,4,opt,name=pagenum,proto3" json:"pagenum,omitempty"`
	Pagesize int64 `protobuf:"varint,3,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
}

func (x *RelationshipRequestWithPagination) Reset() {
	*x = RelationshipRequestWithPagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationshipRequestWithPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipRequestWithPagination) ProtoMessage() {}

func (x *RelationshipRequestWithPagination) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipRequestWithPagination.ProtoReflect.Descriptor instead.
func (*RelationshipRequestWithPagination) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{4}
}

func (x *RelationshipRequestWithPagination) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RelationshipRequestWithPagination) GetPagenum() int64 {
	if x != nil {
		return x.Pagenum
	}
	return 0
}

func (x *RelationshipRequestWithPagination) GetPagesize() int64 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

// A `ListRequest` defines various url and query parameters that could be
// passed in a HTTP **GET** request to a collection resource. All collection
// resources are expected to support pagination. Majority of the request
// parameters are identical or similar to [jsonapi](http://jsonapi.org).
type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// include query parameter to retrieve any particular or particular
	// combination of relationships. Multiple include values are delimited by
	// comma(,).
	//
	// For example,
	// /{resource_name}/13?include=baz
	// /{resource_name}/13?include=baz,bot
	Include string `protobuf:"bytes,1,opt,name=include,proto3" json:"include,omitempty"`
	// fields query parameter to retrieve any particular or any particular
	// combination of attributes. Multiple fields values are delimited by comma(,).
	//
	// For example
	// /{resource_name}/29?fields=foo
	// /{resource_name}/?fields=foo,bar
	Fields string `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	// The page number to fetch
	Pagenum int64 `protobuf:"varint,4,opt,name=pagenum,proto3" json:"pagenum,omitempty"`
	// Number of records per page
	Pagesize int64 `protobuf:"varint,5,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	// The `filter` query parameter restricts the data return by the
	// collection. To use it, supply an attribute to filter, followed by a
	// filter expression. It uses the following syntax...
	//        attribute operator expression
	// attribute - Any one of the valid attribute of the resource.
	// operator - Defines the type of filter match to use. It could be any of
	// the following four and all of them should be URL-encoded.
	//
	//              ==  Equals (URL encoding is %3D%3D)
	//              !=  Not equals
	//              =@  Contains substring
	//              !@  Not contains substring
	//
	// expression - The value that will be included or excluded from the
	// result. URL-reserved characters must be URL-encoded.
	// For example, the following filter returns all users with last name `Gag`.
	//           /users?filter=last_name%3D%3Dgag
	//
	// Filter can be combined using OR or AND boolean logic.
	//   * The OR is represented using a comma(,).
	//   * The AND is represented using a semi-colon(;).
	//   * AND and OR operators can be combined and AND takes precedence over OR.
	Filter string `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetInclude() string {
	if x != nil {
		return x.Include
	}
	return ""
}

func (x *ListRequest) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

func (x *ListRequest) GetPagenum() int64 {
	if x != nil {
		return x.Pagenum
	}
	return 0
}

func (x *ListRequest) GetPagesize() int64 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *ListRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// A `SimpleListRequest` is identical to `ListRequest` except it does not support
// pagination. The rest of the parameters are identical to `ListRequest` definition.
type SimpleListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// include query parameter to retrieve any particular or particular
	// combination of relationships. Multiple include values are delimited by
	// comma(,).
	//
	// For example,
	// /{resource_name}/13?include=baz
	// /{resource_name}/13?include=baz,bot
	Include string `protobuf:"bytes,1,opt,name=include,proto3" json:"include,omitempty"`
	// fields query parameter to retrieve any particular or any particular
	// combination of attributes. Multiple fields values are delimited by comma(,).
	//
	// For example
	// /{resource_name}/29?fields=foo
	// /{resource_name}/?fields=foo,bar
	Fields string `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	// The `filter` query parameter restricts the data return by the
	// collection. To use it, supply an attribute to filter, followed by a
	// filter expression. It uses the following syntax...
	//        attribute operator expression
	// attribute - Any one of the valid attribute of the resource.
	// operator - Defines the type of filter match to use. It could be any of
	// the following four and all of them should be URL-encoded.
	//
	//              ==  Equals (URL encoding is %3D%3D)
	//              !=  Not equals
	//              =@  Contains substring
	//              !@  Not contains substring
	//
	// expression - The value that will be included or excluded from the
	// result. URL-reserved characters must be URL-encoded.
	// For example, the following filter returns all users with last name `Gag`.
	//           /users?filter=last_name%3D%3Dgag
	//
	// Filter can be combined using OR or AND boolean logic.
	//   * The OR is represented using a comma(,).
	//   * The AND is represented using a semi-colon(;).
	//   * AND and OR operators can be combined and AND takes precedence over OR.
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *SimpleListRequest) Reset() {
	*x = SimpleListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleListRequest) ProtoMessage() {}

func (x *SimpleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleListRequest.ProtoReflect.Descriptor instead.
func (*SimpleListRequest) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{6}
}

func (x *SimpleListRequest) GetInclude() string {
	if x != nil {
		return x.Include
	}
	return ""
}

func (x *SimpleListRequest) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

func (x *SimpleListRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// A `DeleteRequest` defines the url parameter that must be passed
// to remove a singular resource.
type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An unique identifier, for example:
	// "/users/34"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An unique identifier
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{8}
}

func (x *IdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An unique identifier
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdResponse) Reset() {
	*x = IdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdResponse) ProtoMessage() {}

func (x *IdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdResponse.ProtoReflect.Descriptor instead.
func (*IdResponse) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{9}
}

func (x *IdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HealthzIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HealthzIdRequest) Reset() {
	*x = HealthzIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthzIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzIdRequest) ProtoMessage() {}

func (x *HealthzIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzIdRequest.ProtoReflect.Descriptor instead.
func (*HealthzIdRequest) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{10}
}

func (x *HealthzIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ExistResponse wraps a boolean response
type ExistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// exist or non-existant
	Exist bool `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
}

func (x *ExistResponse) Reset() {
	*x = ExistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodef_api_jsonapi_request_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistResponse) ProtoMessage() {}

func (x *ExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protodef_api_jsonapi_request_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistResponse.ProtoReflect.Descriptor instead.
func (*ExistResponse) Descriptor() ([]byte, []int) {
	return file_protodef_api_jsonapi_request_proto_rawDescGZIP(), []int{11}
}

func (x *ExistResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

var File_protodef_api_jsonapi_request_proto protoreflect.FileDescriptor

var file_protodef_api_jsonapi_request_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6a,
	0x73, 0x6f, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65, 0x66, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x61, 0x70, 0x69, 0x1a, 0x36, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x77, 0x69, 0x74, 0x6b, 0x6f, 0x77, 0x2f, 0x67,
	0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x22, 0x59, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x69,
	0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x3e, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x25, 0x0a,
	0x13, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x21, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67,
	0x65, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65,
	0x6e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x22,
	0x8d, 0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x6e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0x5d, 0x0a, 0x11, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x1f,
	0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x1b, 0x0a, 0x09, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x0a,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x10, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x7a, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x08, 0xe2, 0xdf, 0x1f, 0x04,
	0x10, 0x00, 0x18, 0x02, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0d, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x42,
	0x7a, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x65, 0x65, 0x6d, 0x61, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x61, 0x70, 0x69, 0x42, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x6b, 0x65, 0x73, 0x68, 0x32, 0x30, 0x34, 0x35, 0x2f,
	0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65, 0x65, 0x6d,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6a, 0x73,
	0x6f, 0x6e, 0x61, 0x70, 0x69, 0x3b, 0x6a, 0x73, 0x6f, 0x6e, 0x61, 0x70, 0x69, 0xf8, 0x01, 0x01,
	0xa2, 0x02, 0x08, 0x44, 0x49, 0x43, 0x54, 0x59, 0x41, 0x50, 0x49, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protodef_api_jsonapi_request_proto_rawDescOnce sync.Once
	file_protodef_api_jsonapi_request_proto_rawDescData = file_protodef_api_jsonapi_request_proto_rawDesc
)

func file_protodef_api_jsonapi_request_proto_rawDescGZIP() []byte {
	file_protodef_api_jsonapi_request_proto_rawDescOnce.Do(func() {
		file_protodef_api_jsonapi_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_protodef_api_jsonapi_request_proto_rawDescData)
	})
	return file_protodef_api_jsonapi_request_proto_rawDescData
}

var file_protodef_api_jsonapi_request_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protodef_api_jsonapi_request_proto_goTypes = []interface{}{
	(*GetRequest)(nil),                        // 0: protodef.api.jsonapi.GetRequest
	(*GetEmailRequest)(nil),                   // 1: protodef.api.jsonapi.GetEmailRequest
	(*GetRequestWithFields)(nil),              // 2: protodef.api.jsonapi.GetRequestWithFields
	(*RelationshipRequest)(nil),               // 3: protodef.api.jsonapi.RelationshipRequest
	(*RelationshipRequestWithPagination)(nil), // 4: protodef.api.jsonapi.RelationshipRequestWithPagination
	(*ListRequest)(nil),                       // 5: protodef.api.jsonapi.ListRequest
	(*SimpleListRequest)(nil),                 // 6: protodef.api.jsonapi.SimpleListRequest
	(*DeleteRequest)(nil),                     // 7: protodef.api.jsonapi.DeleteRequest
	(*IdRequest)(nil),                         // 8: protodef.api.jsonapi.IdRequest
	(*IdResponse)(nil),                        // 9: protodef.api.jsonapi.IdResponse
	(*HealthzIdRequest)(nil),                  // 10: protodef.api.jsonapi.HealthzIdRequest
	(*ExistResponse)(nil),                     // 11: protodef.api.jsonapi.ExistResponse
}
var file_protodef_api_jsonapi_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protodef_api_jsonapi_request_proto_init() }
func file_protodef_api_jsonapi_request_proto_init() {
	if File_protodef_api_jsonapi_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protodef_api_jsonapi_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestWithFields); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationshipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationshipRequestWithPagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthzIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodef_api_jsonapi_request_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protodef_api_jsonapi_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protodef_api_jsonapi_request_proto_goTypes,
		DependencyIndexes: file_protodef_api_jsonapi_request_proto_depIdxs,
		MessageInfos:      file_protodef_api_jsonapi_request_proto_msgTypes,
	}.Build()
	File_protodef_api_jsonapi_request_proto = out.File
	file_protodef_api_jsonapi_request_proto_rawDesc = nil
	file_protodef_api_jsonapi_request_proto_goTypes = nil
	file_protodef_api_jsonapi_request_proto_depIdxs = nil
}
